In [ ]:
#12March

NUMPY CRASH COURSE 

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
CREATING ARRAY

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [ ]:
#pip install numpy

In [18]:
import numpy as np

In [20]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
type(arr)

numpy.ndarray

In [24]:
type(my_list)

list

In [ ]:
#arange

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(3.0)

array([0., 1., 2.])

In [30]:
np.arange(20,10)#1arg<2arg

array([], dtype=int32)

In [32]:
np.arange(16,10)

array([], dtype=int32)

In [34]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [38]:
np.zeros(3)#parameters tunning

array([0., 0., 0.])

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(2,10)

TypeError: Cannot interpret '10' as a data type

In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [50]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [52]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [60]:
np.ones(3)

array([1., 1., 1.])

In [64]:
np.ones(4,dtype= int)

array([1, 1, 1, 1])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [138]:
np.twos((2,3))#two is not a function numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [140]:
np.twos((2,4))#two is not a function of numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [142]:
np.three((2,3))#three is not a function of numpy

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
import numpy as np

In [84]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
np.arange(1,13).reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [88]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [92]:
np.random.rand(4)

array([0.25802461, 0.51626544, 0.2228954 , 0.83309844])

In [134]:
np.random.rand(4)

array([0.37745689, 0.55518246, 0.60938768, 0.98592315])

In [96]:
np.random.randint(2,4)

2

In [100]:
random.rand(4)

NameError: name 'random' is not defined

In [102]:
np.random.randint(2.20)#2nd argument is exclusive

0

In [104]:
np.random.randint(1,6,4)

array([4, 5, 1, 4])

In [106]:
np.random.rand(3,5)

array([[0.90994127, 0.30539008, 0.07806206, 0.20158876, 0.92127985],
       [0.46674982, 0.20428973, 0.27876132, 0.70922776, 0.70249071],
       [0.47983467, 0.64666504, 0.80501355, 0.61842002, 0.82230045]])

In [112]:
np.random.randint(30,20,10)

ValueError: low >= high

In [114]:
np.random.randint(1)

0

In [120]:
np.random.rand(3,2)

array([[0.39422966, 0.28506294],
       [0.83498315, 0.81591733],
       [0.06127122, 0.41414206]])

In [122]:
np.random.rand(5)

array([0.70202429, 0.29624412, 0.92852828, 0.73519956, 0.98549252])

In [124]:
np.random.rand(3,5,4)

array([[[0.23176516, 0.25121924, 0.89407869, 0.10488642],
        [0.0680523 , 0.04720533, 0.71538749, 0.24449619],
        [0.23814833, 0.37409644, 0.61738028, 0.83417396],
        [0.66200775, 0.04535191, 0.37353678, 0.96234299],
        [0.96025837, 0.72886058, 0.15254306, 0.89584309]],

       [[0.65416184, 0.51160785, 0.93889044, 0.64497161],
        [0.63947932, 0.69144142, 0.15894677, 0.06373791],
        [0.81716223, 0.7747411 , 0.88551353, 0.00164809],
        [0.90446556, 0.60860441, 0.97991397, 0.60877381],
        [0.86687919, 0.83855718, 0.25709544, 0.16376495]],

       [[0.61103871, 0.43325152, 0.1968294 , 0.22871993],
        [0.97034148, 0.81666411, 0.01038823, 0.3973698 ],
        [0.97518169, 0.12315728, 0.63687143, 0.09755728],
        [0.69447574, 0.1085721 , 0.51816289, 0.89749155],
        [0.09620494, 0.81408744, 0.73283538, 0.14465861]]])

In [130]:
np.random.randint(10,20,30)

array([15, 19, 10, 11, 17, 19, 16, 19, 16, 16, 12, 13, 11, 14, 13, 19, 12,
       13, 13, 19, 13, 11, 19, 10, 15, 10, 19, 16, 13, 17])

In [132]:
np.random.randint(3,5)

4

In [146]:
np.random.randint(6,5,4)

ValueError: low >= high

In [150]:
np.random.rand(7)

array([0.00565037, 0.15940696, 0.54693104, 0.02123196, 0.64054684,
       0.03018509, 0.20652479])